language: generic
os: linux
services:
  - docker

before_install:
  - docker build -t malware94/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true malware94/react-test npm run test -- --coverage

after_success:
  - docker build -t malware94/multi-client ./client
  - docker build -t malware94/multi-nginx ./nginx
  - docker build -t malware94/multi-server ./server
  - docker build -t malware94/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Tagging images before upload
  - docker commit complex-client-1 rmiport/multi-client
  - docker commit complex-nginx-1 rmiport/multi-nginx
  - docker commit complex-api-1 rmiport/multi-server
  - docker commit complex-worker-1 rmiport/multi-worker
  # Take those images and push them to docker hub
  - docker push rmiport/multi-client
  - docker push rmiport/multi-nginx
  - docker push rmiport/multi-server
  - docker push rmiport/multi-worker
  